### ISSUE TITLE
[bug] sfdk engine start with podman fail

### ISSUE THREAD

**Issue by savegame** [sailfishos/sailfish-qtcreator#326]
Sfdk tool run
```sh
docker inspect sailfish-os-build-engine --format={{json .Config.Labels}}
```
its get error: 
```sh
".Config.Labels}}": invalid reference format
```
because `{{json .Config.Labels}}` should be in quote
```sh
docker inspect sailfish-os-build-engine --format="{{json .Config.Labels}}"
```
seems can be fixed with in file
**src/libs/sfdk/dockervirtualmachine.cpp : (lin 187)**
```c++
arguments.append("--format=\"{{json .Config.Labels}}\"");
```
i am already fork project, and fix it, if its helps, i will make PR

**Comment by martyone** [comment]
Hm, this seems suspicious to me. I am worried if 1) it fixes the root cause and 2) if it doesn't fix one case while breaking others. Isn't that a bug on podman side?

Could you please try running it with `export QT_LOGGING_RULES='sfdk.vms*.debug=true'` and paste the log? Also could you please add some details on you environment?

**Comment by savegame** [comment]
it still not work with **podman**, but looks like its **podman** bug, i think i should close this issue for a while
